language: python
install:
- pip install coveralls
- pip install "Django${DJANGO}"
script:
- python setup.py test
after_success:
- coveralls
matrix:
  include:
  - python: 3.4
    env: DJANGO=">=1.8,<1.9"
  - python: 3.4
    env: DJANGO=">=1.9,<1.10"
  - python: 3.5
    env: DJANGO=">=1.10,<1.11"
  - python: 3.5
    env: DJANGO=">=1.11,<1.12"
  - python: pypy3
    env: DJANGO=">=1.8,<1.9"
  - python: pypy
    env: DJANGO=">=1.9,<1.10"
